(defun my/goto-line-beginning-or-indent (&optional $position)
  (interactive)
  (or $position (setq $position (point)))
  (let (($starting-position (progn (back-to-indentation) (point))))
    (if (eq $starting-position $position)
      (move-beginning-of-line 1))))

(defun open-atom ()
  (interactive)
  (call-process "atom" nil nil nil buffer-file-name))